name: Lab Manager

env:
  TERRAFORM_VERSION: 1.11.0

on:
  workflow_dispatch: # Allows manual trigger via API
    inputs:
      cloud:
        description: "Cloud provider"
        type: choice
        options:
          - "aws"
          - "azure"
        required: true
        default: "aws"
      lab:
        description: "Lab name"
        type: choice
        options:
          - "basic"
        required: true
        default: "basic"
      action:
        description: "Terraform action"
        type: choice
        options:
          - "apply"
          - "destroy"
        required: true
        default: "apply"
      student_username:
        description: "Unique student username"
        required: true

jobs:
  terraform:
    name: Create or Destroy Lab
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Verify AWS CLI
        run: aws s3 ls # Example: List S3 buckets to confirm AWS access

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: ${{ github.workspace }}/${{ github.event.inputs.cloud }}/labs/${{ github.event.inputs.lab }}
        run: |
          pwd
          ls -la
          terraform --version
          terraform init -reconfigure -backend-config=bucket=${{ vars.TF_STATE_BUCKET }} -backend-config=key=labs/${{ github.event.inputs.student_username }}/terraform.tfstate -backend-config=region=${{ vars.AWS_REGION }} -backend-config=encrypt=true -backend-config=use_lockfile=true

      - name: Terraform Apply
        working-directory: ${{ github.workspace }}/${{ github.event.inputs.cloud }}/labs/${{ github.event.inputs.lab }}
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve -var='student_username=${{ github.event.inputs.student_username }}'

      - name: Terraform Destroy
        working-directory: ${{ github.workspace }}/${{ github.event.inputs.cloud }}/labs/${{ github.event.inputs.lab }}
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve -var='student_username=${{ github.event.inputs.student_username }}'

      - name: Create output file
        working-directory: ${{ github.workspace }}/${{ github.event.inputs.cloud }}/labs/${{ github.event.inputs.lab }}
        run: echo "{" > ${{ github.event.inputs.student_username }}json

      - name: Get Terraform Outputs
        working-directory: ${{ github.workspace }}/${{ github.event.inputs.cloud }}/labs/${{ github.event.inputs.lab }}
        run: |
          echo '"STUDENT_USERNAME": "$(terraform output -raw student_username)",' >> ${{ github.event.inputs.student_username }}json
          echo "STUDENT_PASSWORD": "$(terraform output -raw student_password)",' >> ${{ github.event.inputs.student_username }}json
          echo "AWS_CONSOLE_URL": "$(terraform output -raw aws_console_url)"' >> ${{ github.event.inputs.student_username }}json
          echo "}" >> ${{ github.event.inputs.student_username }}json

      - name: Show Outputs
        run: cat ${{ github.workspace }}/${{ github.event.inputs.cloud }}/labs/${{ github.event.inputs.lab }}/${{ github.event.inputs.student_username }}json

      - name: Save Outputs
        uses: actions/upload-artifact@v4
        with:
          name: terraform-outputs
          path: |
            ${{ github.workspace }}/${{ github.event.inputs.cloud }}/labs/${{ github.event.inputs.lab }}/${{ github.event.inputs.student_username }}json
